// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Data;

namespace Shop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220324095216_InitialCreate4")]
    partial class InitialCreate4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 0,
                            Name = "Комп'ютери та ноутбуки"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 0,
                            Name = "Смартфони"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 0,
                            Name = "Побутова техніка"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 0,
                            Name = "Дача, сад, город"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 0,
                            Name = "Спорт і захоплення"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 0,
                            Name = "Офіс, школа, книги"
                        });
                });

            modelBuilder.Entity("Shop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ShortDesc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "test",
                            Image = "https://video.rozetka.com.ua/img_superportal/kompyutery_i_noutbuki/noutbuki.png",
                            Name = "ПК Х123434",
                            Price = 436765.0,
                            ShortDesc = "figna"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Ми представляємо вам найпотужнішу, саму оснащену, ударотривкий та найефективнішу версію смартфона 2021 року від румунської компанії iHunt .",
                            Image = "https://content2.rozetka.com.ua/goods/images/big/186736679.jpg",
                            Name = "iHunt Titan P13000 PRO 2021",
                            Price = 13940.0,
                            ShortDesc = "figna"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Холодильники з системою NeoFrost ",
                            Image = "https://content1.rozetka.com.ua/goods/images/big/175324656.jpg",
                            Name = "BEKO CNA295K20XP",
                            Price = 10999.0,
                            ShortDesc = "figna"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Ланцюгова пила Bosch UniversalChain ",
                            Image = "https://content.rozetka.com.ua/goods/images/big/144435754.jpg",
                            Name = "Bosch UniversalChain 40",
                            Price = 3958.0,
                            ShortDesc = "figna"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Велосипед Champion Spark 29 ",
                            Image = "https://content2.rozetka.com.ua/goods/images/big/44538732.jpg",
                            Name = "Champion Spark 29 19.5 Black-neon yellow-white",
                            Price = 5460.0,
                            ShortDesc = "figna"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Description = "ВНабір паперу офісного Zoom Stora Enso А4 80 г/м2 клас С + 5 пачок по 500 аркушів Біла ",
                            Image = "https://content2.rozetka.com.ua/goods/images/big/252699020.jpg",
                            Name = "Zoom Stora Enso А4 80 г/м2 клас С + 5 пачок по 500 аркушів Біла",
                            Price = 1199.0,
                            ShortDesc = "figna"
                        });
                });

            modelBuilder.Entity("Shop.Models.Product", b =>
                {
                    b.HasOne("Shop.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shop.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
